//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : adress.java
//  @ Date : 2019-07-04
//  @ Author : 
//
//




public class adress1 {
	public String name; //이름
	public int age;	//나이
	public String gender; //성별
	public String adress; //주소
	public String phone; //연락처
	public String email; //이메일
	public void setScore(int newScore) {
	
	}
	
	public adress1(String name, int age, String gender,
			String adress,String phone,String email ) {
		this.name=name;
		this.age=age;
		this.gender=gender;
		this.adress=adress;
		this.phone=phone;
		this.email=email;
	}
	
}
